# Login information file (placeholder).

bluesky:
  handle: Fake
  password: Fake

instagram:
  username: Fake
  password: Fake

mastodon:
  access_token: Fake
  api_base_uri: Fake
  client_key: Fake
  client_secret: Fake

x:
  access_token_secret: Fake
  access_token: Fake
  bearer_token: Fake
  consumer_key: Fake
  consumer_secret: Fake
